# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deployment

on:
    push:
        branches: ["main"]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: corepack enable
            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "yarn"
            - run: yarn install --frozen-lockfile
            - run: yarn build
            - name: Archive production artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: dist
                  path: |
                      dist
    deploy:
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - name: Download a single artifact
              uses: actions/download-artifact@v4
              with:
                  name: dist
                  path: ./dist
            # デフォルトではgh-pageeブランチにpushする
            - name: Push gh-pages branch
              uses: peaceiris/actions-gh-pages@v3
              with:
                  # Deploy keysやPersonal access Tokensも使用可能
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
                  user_name: github-actions
                  user_email: github-actions@github.com
